Deploy and verify
otterspace-xyz/otterspace-contracts pull request #55
Opened 2022-07-12 13:35 UTC by grp06

2022-07-12 14:20 UTC, rahulrumalla commented
Could you add some documentation in readme to clarify how/when to use this for developers, please?

2022-07-12 14:21 UTC, rahulrumalla requested changes

2022-07-13 08:49 UTC, grp06 commented on scripts/deploy_and_verify.sh
> +source .env.rinkeby
done

2022-07-13 08:49 UTC, grp06 commented
> Could you add some documentation in readme to clarify how/when to use this for developers, please?



> Could you add some documentation in readme to clarify how/when to use this for developers, please?

done

2022-07-13 09:18 UTC, rahulrumalla commented on readme.md
> +-   create a `.env` file or (`.env.whatever`) matching the parameters seen in `./scripts/deploy_and_verify.sh`
```suggestion
-   create a `.env` file or (`.env.network`) matching the parameters seen in `./scripts/deploy_and_verify.sh`, and pass it as a parameter when running the script as seen below
```

2022-07-13 09:18 UTC, rahulrumalla commented on readme.md
> +-   run `./scripts/deploy_and_verify.sh .env.whatever`
```suggestion
-   run `./scripts/deploy_and_verify.sh .env.network`
```

2022-07-13 09:20 UTC, rahulrumalla commented
Thanks for addressing previous comments. One addition comes to mind here i.e., providing a .env.example by convention that is not git ignored. This would help a developer know easily what keys they need rather than extrapolate it by understanding the script. Reduces human error this way I feel. Could we add .env.example and update readme docs as needed, please?

2022-07-13 12:43 UTC, rahulrumalla approved these changes

2022-07-13 12:43 UTC, merged